### ISSUE TITLE
Most tests fail using Django and pytest-django

### ISSUE THREAD

**Issue by max-wittig** [pytest-dev/pytest-xdist#1151]
I ran it once and everything was green, but on the second run the whole terminal is full of these messages:

```sh
poetry run pytest -n auto
============================================================= test session starts =============================================================
platform darwin -- Python 3.12.7, pytest-8.3.3, pluggy-1.5.0
django: version: 5.1.1, settings: codeapps.settings.local (from env)
rootdir: /Users/max/dir
configfile: pyproject.toml
plugins: Faker-30.8.1, cov-6.0.0, freezegun-0.4.2, deadfixtures-2.2.1, django-test-migrations-1.4.0, django-4.9.0, clarity-1.0.1, bdd-7.3.0, unordered-0.6.1, anyio-4.6.2.post1, xdist-3.6.1
10 workers [1351 items]   
EEEEEEE...E....E..........E...........E............E......E....E....E....E.....E......E...E.....E..............................E.....E. [  9%]
..E........E.........E.........E....E......E....E.......E............E.......E.......E....E...E.......ss......E.........E......E..E.... [ 19%]
ERROR gitlab_cache/tests/test_api_projects.py::test_get_projects_by_parent_group_id_when_group_id_specified_returns_only_filtered_projects - django.db.utils.IntegrityError: duplicate key value violates unique constraint "django_content_type_app_label_model_76bd3d3b_uniq"

=== 666 passed, 3 skipped, 682 errors in 144.22s (0:02:24)
```

---

```toml
[tool.pytest.ini_options]
addopts = "--cov . --cov-report term --cov-report html --cov-report xml --junitxml junit.xml --gherkin-terminal-reporter --ignore=e2e_tests"
bdd_features_base_dir = "features/"
filterwarnings = "ignore"
junit_family = "xunit2"
```
