### ISSUE TITLE
Plugin raises error with `--pdb` option despite using `-n0`

### ISSUE THREAD

**Issue by atugushev** [pytest-dev/pytest-xdist#937]
```toml
# pyproject.toml
[tool.pytest.ini_options]
addopts = "--dist=load"
```

```commandline
$ pytest  --pdb -n0
ERROR: --pdb is incompatible with distributing tests; try using -n0 or -nauto.
```

As you can see,  `-n0` is already passed. However, pytest still suggests using `-n0` to address the issue.

#### Solution

`-n0` should imply `--dist=no`.
